import tailwindcss from '@tailwindcss/vite'
import type { PluginOption } from 'vite'

export default defineNuxtConfig({
  compatibilityDate: '2026-07-01',
  devtools: { enabled: false },
  experimental: {
    // Non-standard watcher value kept intentionally for the local sandbox setup;
    // Nuxt's published type only lists chokidar/parcel/chokidar-granular.
    // @ts-expect-error -- accepted at runtime, narrower than the published union type
    watcher: 'builder',
  },

  modules: ['@pinia/nuxt', '@nuxtjs/i18n', '@nuxtjs/color-mode'],

  css: ['~/assets/css/main.css'],

  vite: {
    // Cast: @tailwindcss/vite may resolve against a second vite instance in CI,
    // which makes the Plugin type nominally incompatible
    plugins: [tailwindcss() as unknown as PluginOption],
    server: {
      watch: {
        usePolling: true,
        interval: 500,
        ignored: [
          '**/.git/**',
          '**/.nuxt/**',
          '**/.output/**',
          '**/.turbo/**',
          '**/.tokensave/**',
          '**/.serena/**',
          '**/coverage/**',
          '**/dist/**',
          '**/node_modules/**',
        ],
      },
    },
  },

  build: {
    // Workspace packages ship TS/Vue source — let Nuxt transpile them
    transpile: ['@print-shop/ui', '@print-shop/utils', '@print-shop/types', '@print-shop/validators'],
  },

  runtimeConfig: {
    // Server-only: where nitro routes (sitemap) reach the Express API directly
    apiOrigin: process.env.API_PROXY_TARGET?.replace(/\/api$/, '') ?? 'http://localhost:3001',
    public: {
      apiBase: '/api',
      siteUrl: process.env.NUXT_PUBLIC_SITE_URL ?? 'http://localhost:3000',
      ga4MeasurementId: '',
      metaPixelId: '',
    },
  },

  nitro: {
    devProxy: {
      '/api': { target: process.env.API_PROXY_TARGET ?? 'http://localhost:3001/api', changeOrigin: true },
    },
    routeRules: {
      '/api/**': { proxy: `${process.env.API_PROXY_TARGET ?? 'http://localhost:3001/api'}/**` },
    },
  },

  colorMode: {
    // Dark is the primary brand theme; stored in localStorage, System selectable
    preference: 'dark',
    fallback: 'dark',
    dataValue: 'theme',
    classSuffix: '',
    storageKey: 'print-shop-color-mode',
  },

  i18n: {
    strategy: 'prefix_except_default',
    defaultLocale: 'de',
    // Absolute base for hreflang/canonical links generated by useLocaleHead
    baseUrl: process.env.NUXT_PUBLIC_SITE_URL ?? 'http://localhost:3000',
    lazy: true,
    langDir: 'locales',
    detectBrowserLanguage: false,
    locales: [
      { code: 'de', language: 'de-DE', name: 'Deutsch', file: 'de.json' },
      { code: 'en', language: 'en-US', name: 'English', file: 'en.json' },
      { code: 'pl', language: 'pl-PL', name: 'Polski', file: 'pl.json' },
      { code: 'fr', language: 'fr-FR', name: 'Français', file: 'fr.json' },
      { code: 'nl', language: 'nl-NL', name: 'Nederlands', file: 'nl.json' },
      { code: 'cs', language: 'cs-CZ', name: 'Čeština', file: 'cs.json' },
    ],
  },

  app: {
    head: {
      title: '3D Print Shop',
      htmlAttrs: { lang: 'de' },
      meta: [
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'description', content: 'Individuell konfigurierbare 3D-Druck-Artikel' },
      ],
    },
  },
})
